# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: #eee;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.025, y1:0.238636, x2:1, y2:1, stop:0 rgba(110, 69, 226, 255), stop:1 rgba(136, 211, 206, 255))")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(150, 100, 150, 100)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(500, 500))
        self.widget.setStyleSheet("background-color: white;\n"
"border-radius: 20px;\n"
"box-shadow: 4px 4px 18px 28px rgba(34, 60, 80, 0.2);\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.title = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Play")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.login_input = QtWidgets.QLineEdit(parent=self.widget)
        self.login_input.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"margin: 0 50px;\n"
"height: 30px;\n"
"padding: 10px 0 10px 20px;\n"
"border-radius: 10px;\n"
"font-size: 20px;")
        self.login_input.setText("")
        self.login_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.login_input.setObjectName("login_input")
        self.verticalLayout_2.addWidget(self.login_input)
        self.password_input = QtWidgets.QLineEdit(parent=self.widget)
        self.password_input.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"margin: 0 50px;\n"
"height: 30px;\n"
"padding: 10px 0 10px 20px;\n"
"border-radius: 10px;\n"
"\n"
"font-size: 20px;")
        self.password_input.setObjectName("password_input")
        self.verticalLayout_2.addWidget(self.password_input)
        self.error_label = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label.sizePolicy().hasHeightForWidth())
        self.error_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Play")
        font.setPointSize(12)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: red;")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_2.addWidget(self.error_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.login_button = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.login_button.setStyleSheet("QPushButton {\n"
"    background-color: #4231ff;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    cursor: pointer;\n"
"    height: 40px;\n"
"    margin: 0px 70px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(10, 12, 162);\n"
"\n"
"}")
        self.login_button.setObjectName("login_button")
        self.verticalLayout_2.addWidget(self.login_button)
        self.recovery_button = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recovery_button.sizePolicy().hasHeightForWidth())
        self.recovery_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.recovery_button.setFont(font)
        self.recovery_button.setStyleSheet("QLabel {\n"
"    margin: 0px 50px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QLabel:hover {    \n"
"    color: rgb(10, 12, 162);\n"
"}")
        self.recovery_button.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.recovery_button.setWordWrap(True)
        self.recovery_button.setObjectName("recovery_button")
        self.verticalLayout_2.addWidget(self.recovery_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тестирующая система"))
        self.title.setText(_translate("MainWindow", "Вход в аккаунт"))
        self.login_input.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.login_button.setText(_translate("MainWindow", "Войти в аккаунт"))
        self.recovery_button.setText(_translate("MainWindow", "Восстановить пароль"))
